/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
import kotlinx.interop.wasm.dom.document
import kotlinx.wasm.jsinterop.setter
import org.mvnsearch.wasm.demo.Welcome


fun main() {
    val demo = document.getElementById("Demo")
    demo.setter("href", "https://www.google.com")
    println(Welcome().hello())
}
